title: Santiago Giraldo Alegría
description: Ingeniero de Sistemas, Universidad del Valle, Colombia
profession: Ingeniero de Sistemas
university: Universidad del Valle, Colombia
linkedin: https://www.linkedin.com/in/santiagogiraldoalegria/
logo: /assets/images/profile.jpg
image: /assets/images/profile.jpg
lang: es-ES
twitter:
  username: Arkaikus_
  card: summary
plugins:
  - jekyll-seo-tag
  - html-proofer
  - rubocop
  - w3c_validators