title: Santiago Giraldo Alegría
description: Ingeniero de Sistemas, Universidad del Valle, Colombia
profession: Ingeniero de Sistemas
university: Universidad del Valle, Colombia
linkedin: https://www.linkedin.com/in/santiagogiraldoalegria/
profile_picture: /assets/images/profile.jpg
lang: es-ES
plugins:
  - jekyll-seo-tag
  - html-proofer
  - rubocop
  - w3c_validators